quarkus:
  devservices:
    enabled: false
  http:
    port: 8081
  datasource:
    db-kind: postgresql
    username: bob
    password: bob
    reactive:
      url: vertx-reactive:postgresql://localhost:5432/smartbarbo
    devservices:
      enabled: false

  hibernate-orm:
    database:
      generation: drop-and-create
    sql-load-script: import.sql

  swagger-ui:
    always-include: true
    path: /swagger-ui

  smallrye-openapi:
    path: /openapi
  oidc:
    auth-server-url: http://localhost:8181/realms/sbo
    client-id: smartbar-backoffice
    application-type: web-app
    credentials:
      secret: tcdzsLyzdGAcSoeWtPZUlwRCWayvSa4s
    tls:
      verification: none
    token-state-manager:
      split-tokens: true
    roles:
      source: accesstoken
